spring:
  datasource:
    url: jdbc:mysql://db:3306/jubas
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: true
    hibernate.ddl-auto: update
    show-sql: true
    properties.hibernate:
      format_sql: true
springdoc:
  api-docs.path: /api-docs
  swagger-ui.path: /swagger-ui.html
