spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/jubas
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: validate
    show-sql: true
    properties.hibernate:
      format_sql: true
  security.    user:
    name: dev
    password: v6x?ByhJ45SA

jwt:
  issuer: JubasBackend
  duration: 600
  keys:
    public: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAstYQb6YM22hN3g10tJ26ltg+fzQZEp7btL5SVVi4PNXFykVoMgZxPLRJ3ua8kWnilffxtNNrpuQDpMstSL0qM46ZiyeTRPs53U97xK1QHXMVyKepk88ghT1uJ9dURI5C0TMYy8dPb7pnOOmVA1xN8kz7wrAgrFpvtlfzZ1znLUcRLeRPrqVd4faYy9byY+0tbxUozahEYQ6P7d7LTGqC+0TT7UDkxd3tBYe3pw2+4xRJJI8+ehQn8KQtE0/wIgmh1RknrFsYSfAZvG9WHnTNEGzqbzRG0tJRYJfloBJf80qbY/e8HhJmm+pGJT1PRs8pDDxvWW5sDc46BU3dH2vF2wIDAQAB
    private: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCy1hBvpgzbaE3eDXS0nbqW2D5/NBkSntu0vlJVWLg81cXKRWgyBnE8tEne5ryRaeKV9/G002um5AOkyy1IvSozjpmLJ5NE+zndT3vErVAdcxXIp6mTzyCFPW4n11REjkLRMxjLx09vumc46ZUDXE3yTPvCsCCsWm+2V/NnXOctRxEt5E+upV3h9pjL1vJj7S1vFSjNqERhDo/t3stMaoL7RNPtQOTF3e0Fh7enDb7jFEkkjz56FCfwpC0TT/AiCaHVGSesWxhJ8Bm8b1YedM0QbOpvNEbS0lFgl+WgEl/zSptj97weEmab6kYlPU9GzykMPG9ZbmwNzjoFTd0fa8XbAgMBAAECggEACmrIu1AvWIp7Wq9q+GhlqYrAHTXCLiD9yEn7zsfjt3t2UYF4f817RB92XBsRqeDCl5zBQhi8oRSQF8XUBfQq5KTuUbpE7FQ7+yW5nmvACm8dOjp1+MusZ8Z7x6tV18Z3our4i0o5WNdBUwHcMb1rNu2ADsemp5N/BV6bKY6yUqNDYfEh2p6DkT4zZEdTeG8dfLKypnUNmyowUlq8CYdoOtHKdZ3EFW5TBuYvevUldb+j8GstnxxAI5KfslKO0yHUP6KYs2XTtCi+ScKDX4bm6waTewqrVoZPMtEqv2LoSGrW/Ex0N2aFH7rH83tKLyNeSGT7g9ibJDBlJ9QZLZP/pQKBgQD6ptXDqzZXtgwkvelsWgPE0d4STUQ+WTtlsIqVbDHxHqqpW+0lzGm3zaDsKVf+1J7xqp4rhldIsnz7ZsvSWiY39DUA6TvzUzJzg8ZgdLWbKxyPiUDS29EGN+K03z501GAN5TYrwQ6j8yvaMRdxNypGcUT5w/5UpF1l6Gpr+Bp9lQKBgQC2pvFSl/IuHzCn2/zDUFGOt2xPUvpMw4nWE65hHJQOJDhxFkqLoIoBTJvUkWq/5VgXVHKQO81I8MhAzKdyZbPo7N8qnlZtn7N1tBi0nNHGK1uneO+BKaAKzo4ft23XptZ5kbRaJ8l75QDVBLqgxgJWiKQ+kqWSg3UY5qdbLgL5rwKBgQDnKWAx4b/vanSOmhshk26wYQDWji3m9nKCGSvmHG9+uVKZeK8gUgIZwmmsA4ElAsBHjpvq9i2fXQVI8gf9yqg+qFkNqwxgHxWDVT9qC5jFLyBa/DEthg6jFn1dZBn8szSW/BJWjejLqWODCg1dm4vAhYwgcPIo66E7b/pd8uWzdQKBgQCLTZGZu3ciQ/l43GfPkm9RWIVLjm6Fo1B5rDL/r6sfifJeFXEvQnZefU4P9gQjbMgdqvNhG6r6aWFhQnSm4/gtupKNz4r9OqLFL2D0RvIaoLDbbnnD2bpM47IzcFNe+Mh0mXKim9uoGUTkMiIgQkRAOSCC9JdAwe/J2Qhkmxf70wKBgQDLmIyKXKotfaR82r5O3GIIj9UxP9QtSuDSFcgclocJRJ3zQYviPjv8TJ5wn9UPRGPMryxcWENyUlXt8yN7oqj6w0nhkEcOY+sllyJEf9tdvCK3oMwGmzpmQS12MpXrusnIBDw2Auu56uqb2hgbfEp40g3BobnRnUGZaYb7Xj4/iQ==

