@url = http://localhost:8080

### GERAR TOKEN DE ACESSO
POST {{url}}/auth
Content-Type: application/json

{
  "email": "admin@jubas.com",
  "password": "12345678"
}

> {% client.global.set("access_token_admin", response.body.accessToken); %}


### CRIAR NOVO USUÁRIO COMO BARBEIRO
POST {{url}}/users
Authorization: Bearer {{access_token_admin}}
Content-Type: application/json

{
  "email": "hoss@jubas.com",
  "password": "12345678",
  "permission": "BARBEIRO"
}


### CADASTRAR UM ATENDIMENTO
POST {{url}}/appointments
Authorization: Barear {{access_token_admin}}
Content-Type: application/json

{
  "employeeId": "1253fc44-45c5-440c-b0d8-1b9a2c5dc919",
  "clientId": "e8cb8b11-508e-4e09-9dbd-6fadf015e28c",
  "specialtyId": "78be8b22-9576-42c9-a819-0e217b10fa30",
  "dateTime": "2024-03-15 17:20"
}


