###
GET http://localhost:8080/appointments/daysOfAttendance

###
PUT http://localhost:8080/appointments/daysOfAttendance
Content-Type: application/json

{
  "intervalOfDays": 5
}

###
GET http://localhost:8080/appointments?date=2024-03-11

###
GET http://localhost:8080/appointments/c010ddeb-5332-428a-b8f1-d513e4ae5fa6


###
POST http://localhost:8080/appointments
Content-Type: application/json

{
"employeeId": "1253fc44-45c5-440c-b0d8-1b9a2c5dc919",
"clientId": "e8cb8b11-508e-4e09-9dbd-6fadf015e28c",
"specialtyId": "78be8b22-9576-42c9-a819-0e217b10fa30",
"dateTime": "2024-03-11 09:20"
}
