@url = http://localhost:8080

### GERAR TOKEN DE ACESSO
POST {{url}}/auth
Content-Type: application/json

{
  "email": "cliente@gmail.com",
  "password": "12345678"
}

> {% client.global.set("access_token_client", response.body.accessToken); %}


### CRIAR NOVO CONTA
POST {{url}}/users
Content-Type: application/json

{
  "email": "joazinho3@gmail.com",
  "password": "12345678",
  "name": "João Meta",
  "cpf": "01012000222"
}

###
GET {{url}}/users

###
GET {{url}}/users?profiles=true

### BUSCAR AGENDA POR DIA
GET {{url}}/appointments?date=2024-03-15

### BUSCAR AGENDA DO DIA FILTADA POR HORA ATUAL
GET {{url}}/appointments?filtered=true

### BUSCAR AGENDA COM HORÁRIOS POSSÍVEIS PARA DETERMINADA ESPECIALIDADE
GET {{url}}/appointments?specialtyId=78be8b22-9576-42c9-a819-0e217b10fa30

### BUSCAR AGENDAMENTO POR ID
GET {{url}}/appointments/be1abe8e-80d2-4443-8fc1-24f4c5a38ce3

### BUSCAR DIAS DE ATENDIMENTO
GET {{url}}/appointments/daysOfAttendance

### CADASTRAR UM ATENDIMENTO
POST {{url}}/appointments
Authorization: Barear {{access_token_client}}
Content-Type: application/json

{
  "employeeId": "1253fc44-45c5-440c-b0d8-1b9a2c5dc919",
  "clientId": "e8cb8b11-508e-4e09-9dbd-6fadf015e28c",
  "specialtyId": "78be8b22-9576-42c9-a819-0e217b10fa30",
  "dateTime": "2024-03-15 17:20"
}
